package com.jufaja.inyedashares.models

data class DataPost (
    var aauser: User? = null,
    var abdate: String = "",
    var acpartyfunda: Double = 0.0,
    var adpartygrowa: Double = 0.0,
    var aepartyperca: Double = 0.0,
    var afpartyvaluea: Double = 0.0,
    var agpartyfundb: Double = 0.0,
    var ahpartygrowb: Double = 0.0,
    var aipartypercb: Double = 0.0,
    var ajpartyvalueb: Double = 0.0,
    var akpartyfundc: Double = 0.0,
    var alpartygrowc: Double = 0.0,
    var ampartypercc: Double = 0.0,
    var anpartyvaluec: Double = 0.0,
    var aopartyfundd: Double = 0.0,
    var appartygrowd: Double = 0.0,
    var aqpartypercd: Double = 0.0,
    var arpartyvalued: Double = 0.0,
    var astotalfunda: Double = 0.0,
    var atmultigrowa: Double = 0.0,
    var autotalgrowa: Double = 0.0,
    var avmultiperca: Double = 0.0,
    var awtotalperca: Double = 0.0,
    var axtotalfundb: Double = 0.0,
    var aymultigrowb: Double = 0.0,
    var aztotalgrowb: Double = 0.0,
    var bamultipercb: Double = 0.0,
    var bbtotalpercb: Double = 0.0,
    var bctotalfundc: Double = 0.0,
    var bdmultigrowc: Double = 0.0,
    var betotalgrowc: Double = 0.0,
    var bfmultipercc: Double = 0.0,
    var bgtotalpercc: Double = 0.0,
    var bhtotalfundd: Double = 0.0,
    var bimultigrowd: Double = 0.0,
    var bjtotalgrowd: Double = 0.0,
    var bkmultipercd: Double = 0.0,
    var bltotalpercd: Double = 0.0,
    var bmtotalabcd: Double = 0.0,
    var bnmultiprofi: Double = 0.0,
    var bototalprofi: Double = 0.0,
    var bppercentagex: Double = 0.0,
    var bqpercentagey: Double = 0.0
        )